### PR TITLE
Click tracking setting options

### PR DESCRIPTION
**Pull request by mark5280**
For a Django project I needed the ability to turn off click tracking of links even though my Sendgrid settings have them activated.  I extended the configuration settings to include click tracking on html and plain text messages.

### CODE REVIEW

**Comment by sklarsa** [comment]
Those new settings are `True` by default (at the sendgrid level)?

**Comment by mark5280** [comment]
Steven - I did some additional API testing via Postman against the GET https://api.sendgrid.com/v3/tracking_settings/click endpoint and my Sendgrid API Key.  

Regardless how I have the settings in my Sendgrid account for HTML and Plain Text click tracking the settings I created (SENDGRID_TRACK_CLICKS_HTML and SENDGRID_TRACK_CLICKS_PLAIN) overrides what is set at the sendgrid level.  This is actually better behavior in my mind as it can be used in more granular way.

The defaults I provided in the pull request enable both html and plain text link tracking.  I believe when you first set up a new Sendgrid account that click tracking is not turned on for either. Given this it might be better to default SENDGRID_TRACK_CLICKS_HTML and SENDGRID_TRACK_CLICKS_PLAIN to False and then, if desired, the developer can set them explicitly to true.  Given this let me know if you agree and I can submit a new pull request with these changed to False.  

Thanks!

**Comment by sklarsa** [comment]
I think we should abide by what sendgrid does by default.  However, my concern is that if we add these settings and set them to `False` by default, existing users that have click tracking turned on in their global configs would no longer get click tracking once they upgrade the django-sendgrid-v5 package.  

Can you update your code so that the click tracking attributes are set ONLY if the settings are present in django settings, otherwise don't add anything to the email object so sendgrid will default to whatever users have set in their default sendgrid settings?

**Comment by mark5280** [comment]
Steve - I did some additional testing and found that email opens (SENDGRID_TRACK_EMAIL_OPENS) works just the same as the click tracking...It overrides whatever the settings might be in the Sendgrid portal.  In your original code you set it as True and then, if there is an explicit setting for the variable you set it to that.  Without explicit setting of the variable it defaults to True which may or may not reflect what it is in the Sendgrid portal settings.  I seem to recall when I've set new accounts up in the past that open tracking may be on by default but I have no recollection of what the default settings of click tracking might have been.  

Without well established defaults on the Sendgrid portal side the only way to make sure that the default behavior of the module would be to query, via the API, those settings and then we likely have to recommend what API key permissions are in place.  If you create a new API key and select Full Access you'll have everything needed to do this query but it's likely overkill.  Perhaps it might be easier to update the README to indicate setting SENDGRID_TRACK_EMAIL_OPENS, SENDGRID_TRACK_CLICKS_HTML, and SENDGRID_TRACK_CLICKS_PLAIN to the desired settings rather than default them to something.

Sorry that this got complicated fast ;) At least we have some new information on setting behavior in the API overrides the Sendgrid portal settings.

Let me know if you have additional thoughts and direction you would recommend.

**Comment by sklarsa** [comment]
I want to limit the set of permissions that we need to run this plugin, and it seems like overkill for a user to create an API Key with "Full Access" permissions when we're only using the escalated permissions to check if they have email/click tracking on by default if nothing is specified.  

I'd say lets default to True, and a user can turn it off explicitly through changing the Django settings.

**Comment by sklarsa** [comment]
Also it appears that @tomasgarzon has been working on this feature in #50.  I'd like to give you both credit in the commit history, so I may end up merging these 2 PRs into 1 before merging it to master (if that's even possible...)

**Comment by mark5280** [comment]
The approach sounds good.  Let me update the code over the next couple of days and I'll get you a fresh PR.  Thanks!

**Comment by sklarsa** [comment]
Closes #58 
Merged by hand

**Pull request closed without merging**
